/**
 * BOSS直聘 CSS 选择器常量。
 * 迁移自 ai-sdk-computer-use/lib/tools/zhipin/constants.ts
 * DOM 结构变更时只需更新此文件。
 */
export const ZHIPIN_SELECTORS = {
  login: {
    notLoggedIn: ".header-login-btn",
  },
  unread: {
    container: ".chat-list-wrap",
    listItem: '[role="listitem"]',
    geekItemWrap: ".geek-item-wrap",
    item: ".chat-item",
    unreadBadge: ".badge-count",
    unreadBadgeNew: ".badge-count.badge-count-common-less",
    unreadBadgeSpan: ".badge-count span",
    unreadDot: ".red-dot",
    figure: ".figure",
    badge: ".badge",
    candidateName: ".candidate-name",
    candidateNameAlt: ".chat-item-name",
    candidateNameSelectors: '[class*="name"], .nickname, .geek-name',
    candidateNameNew: ".geek-name",
    jobTitle: ".source-job",
    lastMessage: ".push-text",
    lastMessageAlt: ".chat-last-msg",
    messageTime: ".time, .time-shadow",
    clickArea: ".chat-item-content",
    unreadCandidates: ".geek-item",
  },
  chat: {
    chatContainer: ".chat-container",
    messageList: ".message-list",
    messageItem: ".message-item",
    messageContent: ".message-content",
    messageText: ".text-content",
    userMessage: ".message-right",
    candidateMessage: ".message-left",
    messageTime: ".message-time",
    senderName: ".sender-name",
    inputBox: ".chat-input",
    inputTextarea: "textarea.chat-input",
    inputEditorId: "#boss-chat-editor-input",
    sendButton: ".btn-send",
    conversationEditor: ".conversation-editor",
    submitButton: ".submit-content .submit",
    submitButtonActive: ".submit-content .submit.active",
    submitContent: ".submit-content",
    sendButtonAlt: ".conversation-editor .submit-content",
    sendIcon: ".submit-content .icon-send",
    systemMessage: ".system-msg",
  },
  chatDetails: {
    candidateInfoContainer: ".base-info-single-container, .base-info-content",
    candidateName: ".name-box, .geek-name, .base-name",
    candidateInfoItem: ".geek-info-item, .base-info-item, .base-info-single-detial > div",
    candidateTag: ".geek-tag, .high-light-boss",
    communicationPosition: ".position-name",
    communicationPositionAlt: ".position-item:not(.expect) .value.high-light-boss",
    candidateExpectContainer: ".position-item.expect",
    candidateExpectValue: ".position-item.expect .value.job",
    candidateExpectSalary: ".position-item.expect .high-light-orange",
    candidatePosition: ".geek-position, .position-name",
    candidatePositionAlt: ".position-content .value, .position-item .value",
    chatMessageContainer: ".conversation-message, .message-list",
    messageItem: ".message-item",
    messageTime: ".message-time .time",
    messageTextSpan: ".text span",
    systemMessage: ".item-system",
    friendMessage: ".item-friend",
    myMessage: ".item-myself",
    resumeMessage: ".item-resume",
    readStatus: ".status-read",
  },
  exchangeWechat: {
    exchangeButtonPath:
      "#container > div:nth-child(1) > div > div.chat-box > div.chat-container > div.chat-conversation > div.conversation-box > div.conversation-operate > div.toolbar-box > div.toolbar-box-right > div.operate-exchange-left > div:nth-child(3) > span.operate-btn",
    exchangeButtonFallback: ".operate-exchange-left .operate-btn",
    confirmDialog: ".exchange-tooltip",
    confirmButton: ".exchange-tooltip .btn-box .boss-btn-primary.boss-btn",
    confirmButtonPath:
      "#container > div:nth-child(1) > div > div.chat-box > div.chat-container > div.chat-conversation > div.conversation-box > div.conversation-operate > div.toolbar-box > div.toolbar-box-right > div.operate-exchange-left > div:nth-child(3) > div > div > span.boss-btn-primary.boss-btn",
    cancelButton: ".exchange-tooltip .btn-box .boss-btn-outline.boss-btn",
    wechatCard: ".message-card-top-wrap",
    wechatCardAlt: '[class*="d-top-text"]',
  },
  username: {
    primary: ".nav-item.nav-logout .user-name",
    fallbacks: [
      "#header > div > div > div.nav-item.nav-logout > div.top-profile-logout.ui-dropmenu.ui-dropmenu-drop-arrow > div.ui-dropmenu-label > div > span.user-name",
      ".ui-dropmenu-label .user-name",
      ".nav-logout .user-name",
      "#header .user-name",
      ".top-profile .user-name",
      ".nav-user .user-name",
      ".user-name",
      '[class*="user-name"]',
      '[class*="username"]',
      '[data-qa="user-name"]',
      ".header-user-name",
      "#header .label-name",
    ] as readonly string[],
  },
  nav: {
    sidebar: ".side-wrap.side-wrap-v2",
    chatLink: '.side-wrap.side-wrap-v2 a[href*="/web/chat/index"]',
    recommendLink: '.side-wrap.side-wrap-v2 a[href*="/web/chat/recommend"]',
  },
  recommend: {
    iframe: "#recommendFrame",
    resumeIframe: 'iframe[src*="c-resume"]',
    filterButton:
      ".recommend-filter .filter-label, .filter-label-wrap .filter-label, .filter-label",
    filterPanel: ".filter-panel",
    candidateItem: "[data-geek], .geek-item",
    candidateName: ".name",
    candidateBaseInfo: ".base-info",
    workExps: ".timeline-wrap.work-exps",
    expectInfo: ".row-flex, .timeline-wrap.expect",
    salaryWrap: ".salary-wrap",
    tagsWrap: ".tags-wrap",
    greetButton: ".btn-greet, .op-btn",
    resumeCanvas: "div#resume > canvas#resume, canvas#resume",
    closeResumeBtn: ".close-btn, .dialog-close",
    closeResumeBtnV2: ".recommendV2 .close-btn",
  },
  candidateProfile: {
    panel: ".candidate-info, .resume-info, .geek-info",
    name: ".candidate-info .name, .geek-info .name",
    age: ".candidate-info .age, .geek-info .age",
    gender: ".candidate-info .gender, .geek-info .gender",
    experience: ".candidate-info .experience, .geek-info .work-exp",
    education: ".candidate-info .education, .geek-info .edu",
    expectedSalary: ".candidate-info .salary, .geek-info .expect-salary",
    expectedPosition: ".candidate-info .position, .geek-info .expect-position",
    activeTime: ".candidate-info .active-time, .geek-info .active",
  },
} as const;

export const TIMING = {
  pageLoad: 5_000,
  elementWait: 3_000,
  shortWait: 1_000,
  clickDelay: 200,
  typeDelay: 50,
  scrollDelay: 300,
  maxRetries: 3,
  retryDelay: 1_000,
  pollInterval: 500,
} as const;
