import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  MODEL_CATALOG_SOURCE_URL,
  trimModelCatalog,
} from "../packages/runtime/src/engine/model-catalog.ts";

const target = resolve(
  import.meta.dirname,
  "../packages/runtime/src/engine/model-catalog-snapshot.ts",
);
const response = await fetch(MODEL_CATALOG_SOURCE_URL, { signal: AbortSignal.timeout(30_000) });
if (!response.ok) {
  throw new Error(`models.dev responded ${String(response.status)}`);
}
const snapshot = trimModelCatalog(await response.json(), new Date().toISOString());
const modelCount = Object.values(snapshot.providers).reduce(
  (sum, models) => sum + Object.keys(models).length,
  0,
);
writeFileSync(
  target,
  [
    "// Generated by scripts/refresh-model-catalog.ts — do not edit by hand.",
    'import type { ModelCatalogData } from "./model-catalog.ts";',
    "",
    `export const MODEL_CATALOG_SNAPSHOT: ModelCatalogData = ${JSON.stringify(snapshot, null, 2)};`,
    "",
  ].join("\n"),
);
execFileSync("npx", ["prettier", "--write", target], { stdio: "inherit" });
console.log(
  `model catalog snapshot: ${String(modelCount)} models, fetchedAt ${snapshot.fetchedAt}`,
);
