// Generated by scripts/refresh-model-catalog.ts — do not edit by hand.
import type { ModelCatalogData } from "./model-catalog.ts";

export const MODEL_CATALOG_SNAPSHOT: ModelCatalogData = {
  fetchedAt: "2026-09-04T03:24:30.232Z",
  providers: {
    "alibaba-cn": {
      "qwen3.7-max": {
        context: 1000000,
      },
      "qwen2-5-72b-instruct": {
        context: 131072,
      },
      "deepseek-r1-distill-qwen-7b": {
        context: 32768,
      },
      "qwen3-next-80b-a3b-thinking": {
        context: 131072,
      },
      "deepseek-v3": {
        context: 65536,
      },
      "qwen2-5-omni-7b": {
        context: 32768,
      },
      "qwen-mt-turbo": {
        context: 16384,
      },
      "deepseek-v3-1": {
        context: 131072,
      },
      "qwen-deep-research": {
        context: 1000000,
      },
      "qwen-vl-max": {
        context: 131072,
      },
      "qwen3-next-80b-a3b-instruct": {
        context: 131072,
      },
      "qwen3-coder-flash": {
        context: 1000000,
      },
      "qwen3-14b": {
        context: 131072,
      },
      "qwen-max": {
        context: 131072,
      },
      "qwen3.6-plus": {
        context: 1000000,
      },
      "moonshot-kimi-k2-instruct": {
        context: 131072,
      },
      "qwen-vl-plus": {
        context: 131072,
      },
      "qwen-omni-turbo-realtime": {
        context: 32768,
      },
      "kimi-k2.6": {
        context: 262144,
      },
      "qwen-flash": {
        context: 1000000,
      },
      "glm-5.2": {
        context: 1000000,
      },
      "qwen-turbo": {
        context: 1000000,
      },
      "qwen3-vl-30b-a3b": {
        context: 131072,
      },
      "qwen-vl-ocr": {
        context: 34096,
      },
      "tongyi-intent-detect-v3": {
        context: 8192,
      },
      "deepseek-v4-flash": {
        context: 1000000,
      },
      "kimi-k2-thinking": {
        context: 262144,
      },
      "qwen3-32b": {
        context: 131072,
      },
      "qwq-plus": {
        context: 131072,
      },
      "qwen3.5-flash": {
        context: 1000000,
      },
      "qwen3-vl-plus": {
        context: 262144,
      },
      "deepseek-v3-2-exp": {
        context: 131072,
      },
      "qwen2-5-7b-instruct": {
        context: 131072,
      },
      "qwen3-coder-30b-a3b-instruct": {
        context: 262144,
      },
      "qwen2-5-math-7b-instruct": {
        context: 4096,
      },
      "qwen3.5-397b-a17b": {
        context: 262144,
      },
      "qwq-32b": {
        context: 131072,
      },
      "deepseek-r1": {
        context: 131072,
      },
      "qwen3-asr-flash": {
        context: 53248,
      },
      "qwen3-omni-flash": {
        context: 65536,
      },
      "deepseek-r1-distill-qwen-1-5b": {
        context: 32768,
      },
      "qwen3.7-flash": {
        context: 1000000,
        input: 991000,
      },
      "qwen2-5-vl-72b-instruct": {
        context: 131072,
      },
      "deepseek-r1-0528": {
        context: 131072,
      },
      "deepseek-r1-distill-qwen-32b": {
        context: 32768,
      },
      "qwen3-max": {
        context: 262144,
      },
      "qwen2-5-coder-32b-instruct": {
        context: 131072,
      },
      "deepseek-r1-distill-llama-70b": {
        context: 32768,
      },
      "qwen2-5-math-72b-instruct": {
        context: 4096,
      },
      "qwen-plus": {
        context: 1000000,
      },
      "MiniMax-M2.5": {
        context: 204800,
      },
      "qwen3-omni-flash-realtime": {
        context: 65536,
      },
      "qwen2-5-vl-7b-instruct": {
        context: 131072,
      },
      "qwen3.6-flash": {
        context: 1000000,
      },
      "qwen3.8-flash": {
        context: 1000000,
      },
      "qwen2-5-14b-instruct": {
        context: 131072,
      },
      "qwen-math-turbo": {
        context: 4096,
      },
      "qwen-plus-character": {
        context: 32768,
      },
      "qwen3.6-max-preview": {
        context: 245800,
      },
      "glm-5": {
        context: 202752,
      },
      "qwen3.8-max": {
        context: 1000000,
      },
      "kimi-k2.5": {
        context: 262144,
      },
      "qwen3-8b": {
        context: 131072,
      },
      "glm-5.1": {
        context: 202752,
      },
      "qwen3-235b-a22b": {
        context: 131072,
      },
      "qwen3.7-plus": {
        context: 1000000,
      },
      "qwen-omni-turbo": {
        context: 32768,
      },
      "deepseek-v4-pro": {
        context: 1000000,
      },
      "qwen3-coder-480b-a35b-instruct": {
        context: 262144,
      },
      "qwen2-5-32b-instruct": {
        context: 131072,
      },
      "qwen2-5-coder-7b-instruct": {
        context: 131072,
      },
      "qwen-long": {
        context: 10000000,
      },
      "deepseek-r1-distill-llama-8b": {
        context: 32768,
      },
      "deepseek-r1-distill-qwen-14b": {
        context: 32768,
      },
      "qwen3-vl-235b-a22b": {
        context: 131072,
      },
      "qwen3.5-plus": {
        context: 1000000,
      },
      "qwen-math-plus": {
        context: 4096,
      },
      "qwen-doc-turbo": {
        context: 131072,
      },
      "qwen-mt-plus": {
        context: 16384,
      },
      "qvq-max": {
        context: 131072,
      },
      "MiniMax/MiniMax-M2.7": {
        context: 204800,
      },
      "siliconflow/deepseek-r1-0528": {
        context: 163840,
      },
      "siliconflow/deepseek-v3.2": {
        context: 163840,
      },
      "siliconflow/deepseek-v3.1-terminus": {
        context: 163840,
      },
      "siliconflow/deepseek-v3-0324": {
        context: 163840,
      },
      "kimi/kimi-k2.5": {
        context: 262144,
      },
      "qwen3-coder-plus": {
        context: 1048576,
      },
    },
    alibaba: {
      "qwen3.7-max": {
        context: 1000000,
      },
      "qwen2-5-72b-instruct": {
        context: 131072,
      },
      "deepseek-v4-flash-0731": {
        context: 1000000,
      },
      "qwen3-coder-plus": {
        context: 1048576,
      },
      "qwen3-next-80b-a3b-thinking": {
        context: 131072,
      },
      "qwen2-5-omni-7b": {
        context: 32768,
      },
      "qwen-mt-turbo": {
        context: 16384,
      },
      "qwen-vl-max": {
        context: 131072,
      },
      "qwen3-next-80b-a3b-instruct": {
        context: 131072,
      },
      "qwen3-coder-flash": {
        context: 1000000,
      },
      "qwen3-14b": {
        context: 131072,
      },
      "qwen-max": {
        context: 32768,
      },
      "qwen3.6-plus": {
        context: 1000000,
      },
      "qwen-vl-plus": {
        context: 131072,
      },
      "qwen-omni-turbo-realtime": {
        context: 32768,
      },
      "qwen3.5-27b": {
        context: 262144,
      },
      "qwen3.5-35b-a3b": {
        context: 262144,
      },
      "qwen-flash": {
        context: 1000000,
      },
      "glm-5.2": {
        context: 1000000,
      },
      "qwen-turbo": {
        context: 1000000,
      },
      "qwen3-livetranslate-flash-realtime": {
        context: 53248,
      },
      "qwen3-vl-30b-a3b": {
        context: 131072,
      },
      "qwen-vl-ocr": {
        context: 34096,
      },
      "qwen3-32b": {
        context: 131072,
      },
      "qwq-plus": {
        context: 131072,
      },
      "qwen3-vl-plus": {
        context: 262144,
      },
      "qwen2-5-7b-instruct": {
        context: 131072,
      },
      "qwen3-coder-30b-a3b-instruct": {
        context: 262144,
      },
      "qwen3.5-397b-a17b": {
        context: 262144,
      },
      "qwen3.6-27b": {
        context: 262144,
      },
      "qwen3-asr-flash": {
        context: 53248,
      },
      "qwen3-omni-flash": {
        context: 65536,
      },
      "qwen2-5-vl-72b-instruct": {
        context: 131072,
      },
      "qwen3.6-35b-a3b": {
        context: 262144,
      },
      "qwen3-max": {
        context: 262144,
      },
      "qwen-plus": {
        context: 1000000,
      },
      "qwen3.5-122b-a10b": {
        context: 262144,
      },
      "qwen3-omni-flash-realtime": {
        context: 65536,
      },
      "qwen2-5-vl-7b-instruct": {
        context: 131072,
      },
      "qwen3.6-flash": {
        context: 1000000,
      },
      "qwen3.8-flash": {
        context: 1000000,
      },
      "qwen2-5-14b-instruct": {
        context: 131072,
      },
      "qwen3.6-max-preview": {
        context: 262144,
      },
      "qwen-plus-character-ja": {
        context: 8192,
      },
      "qwen3.8-max": {
        context: 1000000,
      },
      "qwen3-8b": {
        context: 131072,
      },
      "qwen3-235b-a22b": {
        context: 131072,
      },
      "qwen3.7-plus": {
        context: 1000000,
      },
      "qwen-omni-turbo": {
        context: 32768,
      },
      "qwen3-coder-480b-a35b-instruct": {
        context: 262144,
      },
      "qwen2-5-32b-instruct": {
        context: 131072,
      },
      "qwen3-vl-235b-a22b": {
        context: 131072,
      },
      "qwen3.5-plus": {
        context: 1000000,
      },
      "qwen-mt-plus": {
        context: 16384,
      },
      "qvq-max": {
        context: 131072,
      },
    },
    anthropic: {
      "claude-sonnet-4-6": {
        context: 1000000,
      },
      "claude-opus-5": {
        context: 1000000,
      },
      "claude-opus-4-5": {
        context: 200000,
      },
      "claude-fable-5-1": {
        context: 1000000,
      },
      "claude-opus-4-6": {
        context: 1000000,
      },
      "claude-sonnet-4-5-20250929": {
        context: 1000000,
      },
      "claude-opus-4-7": {
        context: 1000000,
      },
      "claude-haiku-4-5-20251001": {
        context: 200000,
      },
      "claude-fable-5": {
        context: 1000000,
      },
      "claude-haiku-4-5": {
        context: 200000,
      },
      "claude-sonnet-4-5": {
        context: 1000000,
      },
      "claude-opus-4-8": {
        context: 1000000,
      },
      "claude-sonnet-5": {
        context: 1000000,
      },
      "claude-opus-4-5-20251101": {
        context: 200000,
      },
    },
    google: {
      "gemma-4-26b-a4b-it": {
        context: 262144,
      },
      "gemini-3.1-pro-preview-customtools": {
        context: 1048576,
      },
      "gemini-3.1-flash-lite-image": {
        context: 65536,
      },
      "lyria-3-clip-preview": {
        context: 1048576,
      },
      "gemini-2.5-flash-image": {
        context: 32768,
      },
      "deep-research-max-preview-04-2026": {
        context: 131072,
      },
      "gemini-3-pro-image": {
        context: 131072,
      },
      "gemini-3.1-pro-preview": {
        context: 1048576,
      },
      "deep-research-preview-04-2026": {
        context: 131072,
      },
      "gemini-2.5-flash-lite": {
        context: 1048576,
      },
      "gemini-2.5-computer-use-preview-10-2025": {
        context: 131072,
      },
      "gemini-3.6-flash": {
        context: 1048576,
      },
      "gemini-3.1-flash-lite": {
        context: 1048576,
      },
      "gemini-3.1-flash-live-preview": {
        context: 131072,
      },
      "gemini-2.5-pro-preview-tts": {
        context: 8192,
      },
      "gemini-3.5-flash": {
        context: 1048576,
      },
      "veo-3.1-generate-preview": {
        context: 480,
      },
      "gemini-3.1-flash-lite-preview": {
        context: 1048576,
      },
      "veo-3.1-fast-generate-preview": {
        context: 480,
      },
      "gemini-2.5-flash-preview-tts": {
        context: 8192,
      },
      "gemini-embedding-001": {
        context: 2048,
      },
      "gemini-3.1-flash-image": {
        context: 65536,
      },
      "gemini-3.5-flash-lite": {
        context: 1048576,
      },
      "gemini-3-pro-image-preview": {
        context: 131072,
      },
      "gemini-3.1-flash-tts-preview": {
        context: 8192,
      },
      "veo-3.1-lite-generate-preview": {
        context: 480,
      },
      "gemini-flash-lite-latest": {
        context: 1048576,
      },
      "gemma-4-31b-it": {
        context: 262144,
      },
      "gemini-embedding-2": {
        context: 8192,
      },
      "gemini-3-flash-preview": {
        context: 1048576,
      },
      "gemini-3.8-flash": {
        context: 1048576,
      },
      "gemini-3.5-live-translate-preview": {
        context: 16384,
      },
      "lyria-3-pro-preview": {
        context: 1048576,
      },
      "gemini-3.7-flash": {
        context: 1048576,
      },
      "gemini-2.5-pro": {
        context: 1048576,
      },
      "gemini-flash-latest": {
        context: 1048576,
      },
      "gemini-3.1-flash-image-preview": {
        context: 65536,
      },
      "gemini-omni-flash-preview": {
        context: 131072,
      },
      "gemini-2.5-flash": {
        context: 1048576,
      },
    },
    deepseek: {
      "deepseek-v4-flash-vision-exp": {
        context: 1000000,
      },
      "deepseek-v4-flash": {
        context: 1000000,
      },
      "deepseek-v4-pro": {
        context: 1000000,
      },
    },
    openai: {
      "gpt-5-nano": {
        context: 400000,
        input: 272000,
      },
      "gpt-4.1-nano": {
        context: 1047576,
      },
      "gpt-4o-2024-05-13": {
        context: 128000,
      },
      "gpt-5-pro": {
        context: 400000,
        input: 272000,
      },
      "gpt-5.6-sol": {
        context: 1050000,
        input: 922000,
      },
      "gpt-4o-2024-08-06": {
        context: 128000,
      },
      "gpt-5.2-pro": {
        context: 400000,
        input: 272000,
      },
      "gpt-5.3-codex-spark": {
        context: 128000,
        input: 100000,
      },
      "gpt-4.1-mini": {
        context: 1047576,
      },
      "gpt-5.4": {
        context: 1050000,
        input: 922000,
      },
      "gpt-4-turbo": {
        context: 128000,
      },
      "gpt-5.1": {
        context: 400000,
        input: 272000,
      },
      o1: {
        context: 200000,
      },
      "gpt-4o": {
        context: 128000,
      },
      "gpt-5.6-luna": {
        context: 1050000,
        input: 922000,
      },
      "gpt-5.3-codex": {
        context: 400000,
        input: 272000,
      },
      "gpt-4o-mini": {
        context: 128000,
      },
      "o1-pro": {
        context: 200000,
      },
      "gpt-4.1": {
        context: 1047576,
      },
      "text-embedding-ada-002": {
        context: 8192,
      },
      "gpt-5.4-nano": {
        context: 400000,
        input: 272000,
      },
      "gpt-5.5-pro": {
        context: 1050000,
        input: 922000,
      },
      "gpt-5.4-mini": {
        context: 400000,
        input: 272000,
      },
      "gpt-3.5-turbo": {
        context: 16385,
      },
      "gpt-5.6": {
        context: 1050000,
        input: 922000,
      },
      "text-embedding-3-small": {
        context: 8191,
      },
      "gpt-5-mini": {
        context: 400000,
        input: 272000,
      },
      "gpt-5.4-pro": {
        context: 1050000,
        input: 922000,
      },
      "text-embedding-3-large": {
        context: 8191,
      },
      "gpt-5.6-terra": {
        context: 1050000,
        input: 922000,
      },
      "gpt-4": {
        context: 8192,
      },
      "gpt-5.2": {
        context: 400000,
        input: 272000,
      },
      "gpt-5": {
        context: 400000,
        input: 272000,
      },
      "gpt-5.2-chat-latest": {
        context: 128000,
      },
      "o4-mini": {
        context: 200000,
      },
      "gpt-realtime-2.1": {
        context: 128000,
        input: 96000,
      },
      "o3-mini": {
        context: 200000,
      },
      o3: {
        context: 200000,
      },
      "o3-pro": {
        context: 200000,
      },
      "gpt-5.3-chat-latest": {
        context: 128000,
      },
      "gpt-5.5": {
        context: 1050000,
        input: 922000,
      },
      "gpt-4o-2024-11-20": {
        context: 128000,
      },
    },
    xai: {
      "grok-4.3": {
        context: 1000000,
      },
      "grok-4.20-0309-reasoning": {
        context: 1000000,
      },
      "grok-4.20-multi-agent-0309": {
        context: 1000000,
      },
      "grok-imagine-image": {
        context: 8000,
      },
      "grok-imagine-video": {
        context: 1024,
      },
      "grok-4.5": {
        context: 500000,
      },
      "grok-build-0.1": {
        context: 256000,
      },
      "grok-imagine-video-1.5": {
        context: 1024,
      },
      "grok-imagine-image-2.0": {
        context: 8000,
      },
      "grok-4.6": {
        context: 500000,
      },
      "grok-imagine-image-quality": {
        context: 8000,
      },
      "grok-4.20-0309-non-reasoning": {
        context: 1000000,
      },
    },
  },
};
