import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const DEFAULT_PROFILE_NAME = "Roll Agent";
const DEFAULT_PROFILE_COLOR = "#6C5CE7";
const PROFILE_DECORATION_MARKER_VERSION = 2;

function markerPath(userDataDir: string): string {
  return join(userDataDir, ".roll-agent-profile-decorated");
}

function safeReadJson(filePath: string): Record<string, unknown> | null {
  try {
    if (!existsSync(filePath)) {
      return null;
    }
    const raw = readFileSync(filePath, "utf-8");
    const parsed: unknown = JSON.parse(raw);
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
      return null;
    }
    return parsed as Record<string, unknown>;
  } catch {
    return null;
  }
}

function safeWriteJson(filePath: string, data: Record<string, unknown>): void {
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, JSON.stringify(data, null, 2));
}

function readMarkerSignature(userDataDir: string): string | undefined {
  try {
    return readFileSync(markerPath(userDataDir), "utf-8").trim();
  } catch {
    return undefined;
  }
}

function createMarkerSignature(input: { readonly name: string; readonly color: string }): string {
  return JSON.stringify({
    version: PROFILE_DECORATION_MARKER_VERSION,
    name: input.name,
    color: input.color,
  });
}

function setDeep(obj: Record<string, unknown>, keys: readonly string[], value: unknown): void {
  let node: Record<string, unknown> = obj;
  for (const key of keys.slice(0, -1)) {
    const next = node[key];
    if (typeof next !== "object" || next === null || Array.isArray(next)) {
      node[key] = {};
    }
    node = node[key] as Record<string, unknown>;
  }
  const lastKey = keys[keys.length - 1];
  if (lastKey !== undefined) {
    node[lastKey] = value;
  }
}

function parseHexRgbToSignedArgbInt(hex: string): number | null {
  const cleaned = hex.trim().replace(/^#/, "");
  if (!/^[\da-fA-F]{6}$/.test(cleaned)) {
    return null;
  }
  const rgb = Number.parseInt(cleaned, 16);
  const argbUnsigned = (0xff << 24) | rgb;
  return argbUnsigned > 0x7fffffff ? argbUnsigned - 0x1_0000_0000 : argbUnsigned;
}

/**
 * Best-effort profile decoration (name + color). Chrome preference keys
 * vary by version; this is conservative and idempotent.
 */
export function decorateManagedProfile(
  userDataDir: string,
  opts?: { name?: string; color?: string },
): void {
  const desiredName = opts?.name ?? DEFAULT_PROFILE_NAME;
  const desiredColor = (opts?.color ?? DEFAULT_PROFILE_COLOR).toUpperCase();
  const markerSignature = createMarkerSignature({
    name: desiredName,
    color: desiredColor,
  });
  if (readMarkerSignature(userDataDir) === markerSignature) {
    return;
  }

  const desiredColorInt = parseHexRgbToSignedArgbInt(desiredColor);

  const localStatePath = join(userDataDir, "Local State");
  const preferencesPath = join(userDataDir, "Default", "Preferences");

  const localState = safeReadJson(localStatePath) ?? {};
  setDeep(localState, ["profile", "info_cache", "Default", "name"], desiredName);
  setDeep(localState, ["profile", "info_cache", "Default", "shortcut_name"], desiredName);
  setDeep(localState, ["profile", "info_cache", "Default", "user_name"], desiredName);
  setDeep(localState, ["profile", "info_cache", "Default", "profile_color"], desiredColor);
  setDeep(localState, ["profile", "info_cache", "Default", "user_color"], desiredColor);
  if (desiredColorInt != null) {
    setDeep(
      localState,
      ["profile", "info_cache", "Default", "profile_color_seed"],
      desiredColorInt,
    );
    setDeep(
      localState,
      ["profile", "info_cache", "Default", "profile_highlight_color"],
      desiredColorInt,
    );
    setDeep(
      localState,
      ["profile", "info_cache", "Default", "default_avatar_fill_color"],
      desiredColorInt,
    );
    setDeep(
      localState,
      ["profile", "info_cache", "Default", "default_avatar_stroke_color"],
      desiredColorInt,
    );
  }
  safeWriteJson(localStatePath, localState);

  const prefs = safeReadJson(preferencesPath) ?? {};
  setDeep(prefs, ["profile", "name"], desiredName);
  setDeep(prefs, ["profile", "profile_color"], desiredColor);
  setDeep(prefs, ["profile", "user_color"], desiredColor);
  if (desiredColorInt != null) {
    setDeep(prefs, ["autogenerated", "theme", "color"], desiredColorInt);
    setDeep(prefs, ["browser", "theme", "user_color2"], desiredColorInt);
  }
  safeWriteJson(preferencesPath, prefs);

  try {
    writeFileSync(markerPath(userDataDir), `${markerSignature}\n`, "utf-8");
  } catch {
    // ignore
  }
}

/**
 * Mark the profile as cleanly exited to prevent Chrome's "restore session" prompt.
 */
export function ensureProfileCleanExit(userDataDir: string): void {
  const preferencesPath = join(userDataDir, "Default", "Preferences");
  const prefs = safeReadJson(preferencesPath) ?? {};
  setDeep(prefs, ["exit_type"], "Normal");
  setDeep(prefs, ["exited_cleanly"], true);
  safeWriteJson(preferencesPath, prefs);
}
